package features.rs.resources;

import java.util.ArrayList;
import java.util.List;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import joist.rs.CollectionLinkBinding;

@Path("/")
public class ServiceRootResource {

  @GET
  @Produces({ "application/xml", "application/json" })
  public List<CollectionLinkBinding> get() {
    List<CollectionLinkBinding> links = new ArrayList<CollectionLinkBinding>();
    CollectionLinkBinding link;
    link = new CollectionLinkBinding();
    link.setName("childs");
    link.setRelativeUrl("/childs");
    links.add(link);
    link = new CollectionLinkBinding();
    link.setName("childFs");
    link.setRelativeUrl("/childFs");
    links.add(link);
    link = new CollectionLinkBinding();
    link.setName("childGs");
    link.setRelativeUrl("/childGs");
    links.add(link);
    link = new CollectionLinkBinding();
    link.setName("codeADomainObjects");
    link.setRelativeUrl("/codeADomainObjects");
    links.add(link);
    link = new CollectionLinkBinding();
    link.setName("grandChilds");
    link.setRelativeUrl("/grandChilds");
    links.add(link);
    link = new CollectionLinkBinding();
    link.setName("historyEntrys");
    link.setRelativeUrl("/historyEntrys");
    links.add(link);
    link = new CollectionLinkBinding();
    link.setName("inheritanceAOwners");
    link.setRelativeUrl("/inheritanceAOwners");
    links.add(link);
    link = new CollectionLinkBinding();
    link.setName("inheritanceASubOnes");
    link.setRelativeUrl("/inheritanceASubOnes");
    links.add(link);
    link = new CollectionLinkBinding();
    link.setName("inheritanceASubTwos");
    link.setRelativeUrl("/inheritanceASubTwos");
    links.add(link);
    link = new CollectionLinkBinding();
    link.setName("inheritanceAThings");
    link.setRelativeUrl("/inheritanceAThings");
    links.add(link);
    link = new CollectionLinkBinding();
    link.setName("inheritanceBBottoms");
    link.setRelativeUrl("/inheritanceBBottoms");
    links.add(link);
    link = new CollectionLinkBinding();
    link.setName("inheritanceBRootChilds");
    link.setRelativeUrl("/inheritanceBRootChilds");
    links.add(link);
    link = new CollectionLinkBinding();
    link.setName("inheritanceCFoo1s");
    link.setRelativeUrl("/inheritanceCFoo1s");
    links.add(link);
    link = new CollectionLinkBinding();
    link.setName("inheritanceCFoo2s");
    link.setRelativeUrl("/inheritanceCFoo2s");
    links.add(link);
    link = new CollectionLinkBinding();
    link.setName("manyToManyABars");
    link.setRelativeUrl("/manyToManyABars");
    links.add(link);
    link = new CollectionLinkBinding();
    link.setName("manyToManyAFoos");
    link.setRelativeUrl("/manyToManyAFoos");
    links.add(link);
    link = new CollectionLinkBinding();
    link.setName("manyToManyAFooToBars");
    link.setRelativeUrl("/manyToManyAFooToBars");
    links.add(link);
    link = new CollectionLinkBinding();
    link.setName("manyToManyBBars");
    link.setRelativeUrl("/manyToManyBBars");
    links.add(link);
    link = new CollectionLinkBinding();
    link.setName("manyToManyBFoos");
    link.setRelativeUrl("/manyToManyBFoos");
    links.add(link);
    link = new CollectionLinkBinding();
    link.setName("manyToManyBFooToBars");
    link.setRelativeUrl("/manyToManyBFooToBars");
    links.add(link);
    link = new CollectionLinkBinding();
    link.setName("oneToOneABars");
    link.setRelativeUrl("/oneToOneABars");
    links.add(link);
    link = new CollectionLinkBinding();
    link.setName("oneToOneAFoos");
    link.setRelativeUrl("/oneToOneAFoos");
    links.add(link);
    link = new CollectionLinkBinding();
    link.setName("oneToOneBBars");
    link.setRelativeUrl("/oneToOneBBars");
    links.add(link);
    link = new CollectionLinkBinding();
    link.setName("oneToOneBFoos");
    link.setRelativeUrl("/oneToOneBFoos");
    links.add(link);
    link = new CollectionLinkBinding();
    link.setName("parents");
    link.setRelativeUrl("/parents");
    links.add(link);
    link = new CollectionLinkBinding();
    link.setName("parentBChildBars");
    link.setRelativeUrl("/parentBChildBars");
    links.add(link);
    link = new CollectionLinkBinding();
    link.setName("parentBChildFoos");
    link.setRelativeUrl("/parentBChildFoos");
    links.add(link);
    link = new CollectionLinkBinding();
    link.setName("parentBParents");
    link.setRelativeUrl("/parentBParents");
    links.add(link);
    link = new CollectionLinkBinding();
    link.setName("parentCBars");
    link.setRelativeUrl("/parentCBars");
    links.add(link);
    link = new CollectionLinkBinding();
    link.setName("parentCFoos");
    link.setRelativeUrl("/parentCFoos");
    links.add(link);
    link = new CollectionLinkBinding();
    link.setName("parentDs");
    link.setRelativeUrl("/parentDs");
    links.add(link);
    link = new CollectionLinkBinding();
    link.setName("parentDChildAs");
    link.setRelativeUrl("/parentDChildAs");
    links.add(link);
    link = new CollectionLinkBinding();
    link.setName("parentDChildBs");
    link.setRelativeUrl("/parentDChildBs");
    links.add(link);
    link = new CollectionLinkBinding();
    link.setName("parentDChildCs");
    link.setRelativeUrl("/parentDChildCs");
    links.add(link);
    link = new CollectionLinkBinding();
    link.setName("parentDToChildCs");
    link.setRelativeUrl("/parentDToChildCs");
    links.add(link);
    link = new CollectionLinkBinding();
    link.setName("parentEs");
    link.setRelativeUrl("/parentEs");
    links.add(link);
    link = new CollectionLinkBinding();
    link.setName("parentFs");
    link.setRelativeUrl("/parentFs");
    links.add(link);
    link = new CollectionLinkBinding();
    link.setName("parentGs");
    link.setRelativeUrl("/parentGs");
    links.add(link);
    link = new CollectionLinkBinding();
    link.setName("primitivess");
    link.setRelativeUrl("/primitivess");
    links.add(link);
    link = new CollectionLinkBinding();
    link.setName("primitivesBs");
    link.setRelativeUrl("/primitivesBs");
    links.add(link);
    link = new CollectionLinkBinding();
    link.setName("primitivesCs");
    link.setRelativeUrl("/primitivesCs");
    links.add(link);
    link = new CollectionLinkBinding();
    link.setName("userTypesAFoos");
    link.setRelativeUrl("/userTypesAFoos");
    links.add(link);
    link = new CollectionLinkBinding();
    link.setName("validationAFoos");
    link.setRelativeUrl("/validationAFoos");
    links.add(link);
    link = new CollectionLinkBinding();
    link.setName("valuesAs");
    link.setRelativeUrl("/valuesAs");
    links.add(link);
    link = new CollectionLinkBinding();
    link.setName("valuesBs");
    link.setRelativeUrl("/valuesBs");
    links.add(link);
    return links;
  }

}
